FROM openjdk:8-jdk-alpine
VOLUME /tmp
COPY com.cabelas.configurationserver-0.0.1-SNAPSHOT.jar /com.cabelas.configurationserver-0.0.1-SNAPSHOT.jar
ENV JAVA_OPTS=""
ENTRYPOINT exec java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /com.cabelas.configurationserver-0.0.1-SNAPSHOT.jar
